# main config file

# image to use, must be Alpine 3.{4,5} based & container python
base_openstack_image: python:2.7-alpine3.5

openstack:
  # local: directory
  # git: via git
  install: local

  # directory or url. Assumption is all src is in same base url or directory
  # can override individual components by defining additional variables
  #   keystone_location: /path/to/somewhere/keystone
  location: /home/goat/src/openstack

  # if OPENSTACK_INSTALL="git", branch to use
  release: newton
