FROM {{ .Values.base_image }}

ENV TZ ":/etc/localtime"

{{ if eq .Values.install "local" -}}
COPY {{ .Values.location }} /src/

{{ end -}}
RUN apk add --no-cache --virtual .base_deps ca-certificates curl libffi libressl sudo tar && \
    apk add --no-cache --virtual .keystone_run_deps apache2 uwsgi
    {{- range .Values.packages }} {{ . }}{{ end }} && \
    apk add --no-cache --virtual .build-deps gcc git libc-dev libffi-dev linux-headers make libressl-dev sqlite-dev zlib-dev
    {{- range .Values.build_packages }} {{ . }}{{ end }} && \
    {{ if eq .Values.install "git" -}}
    git clone -b {{ .Values.branch }} {{ .Values.location }} /src/ && \
    {{ end -}}
    cd /src && \
    pip install . && \
    apk del .build-deps && \
    rm -rf /src ~/.cache
